FAMAndIMS/Controllers/GlobalSettingController/SubCategoryController/SubCategoryController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using FAMAndIMS.Common;
using FAMAndIMS.Data.Model.CommonModel;
using FAMAndIMS.Data.Model.GlobalSettingModel.SubCategoryModel;
using FAMAndIMS.Data.Services.CommonddlServices;
using FAMAndIMS.Data.Services.CommonServices;
using FAMAndIMS.Data.Services.GlobalSettingServices.SubCategoryServices;
using FAMAndIMS.Filter;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net;

namespace FAMAndIMS.Controllers.GlobalSettingController.SubCategoryController
{
    [Authorize]
    public class SubCategoryController : Controller
    {
        private readonly INotyfService _notyfService;
        private readonly ISubCategoryServices _subCategoryServices;
        private readonly ICommonddlService _commonddlService;
        private readonly ICommonServices _commonServices;

        public SubCategoryController(INotyfService notyfService, ISubCategoryServices subCategoryServices, ICommonddlService commonddlService, ICommonServices commonServices)
        {
            _notyfService = notyfService;
            _subCategoryServices = subCategoryServices;
            _commonddlService = commonddlService;
            _commonServices=commonServices;
        }
        #region Index
        [MenuAccess]
        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] SubCategoryDto subCategoryDto)
        {
            Response.Headers["Cache-Control"] = "no-store, no-cache, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "0";
            ViewBag.view = HttpContext.Items["view"];
            ViewBag.create = HttpContext.Items["create"];
            ViewBag.delete = HttpContext.Items["delete"];
            ViewBag.update = HttpContext.Items["update"];
            var subCategoryList = await _subCategoryServices.GetSubCategoryList(subCategoryDto);
            if (WebHelper.IsAjaxRequest(Request))
            {
                return PartialView("_SubCategoryIndex", subCategoryList);
            }
            return View(subCategoryList);

        }
        #endregion

        #region Save SubCategory
        [HttpGet]
        public async Task<IActionResult> SaveSubCategory()
        {
            var categoryDdlList = await _commonddlService.GetCategoryDDL();
            ViewBag.categoryDdlList = new SelectList(categoryDdlList, "Value", "Text");
            return PartialView();
        }
        [HttpPost]
        [LogUserActivity(UserActionTypes.SaveSubCategory)]
        public async Task<IActionResult> SaveSubCategory(SubCategoryVm subCategoryVm)
        {
            var categoryDdlList = await _commonddlService.GetCategoryDDL();
            ViewBag.categoryDdlList = new SelectList(categoryDdlList, "Value", "Text");
            if (!ModelState.IsValid)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView();
            }
            else
            {
                var responseMessage = await _subCategoryServices.SaveSubCategory(subCategoryVm);
                if (responseMessage.ReturnId > 0)
                {
                    _notyfService.Success(responseMessage.Msg);
                    return Ok();
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    var errors = new List<string> { responseMessage.Msg };
                    ViewBag.Error = errors;
                    return PartialView();
                }
            }
        }
        #endregion

        #region Update SubCategory

        [HttpGet]
        public async Task<IActionResult> UpdateSubCategory(int id)
        {
            var categoryDdlList = await _commonddlService.GetCategoryDDL();
            ViewBag.categoryDdlList = new SelectList(categoryDdlList, "Value", "Text");
            var data = await _subCategoryServices.GetSubCategoryById(id);
            return PartialView(data);
        }

        [HttpPost]
        [LogUserActivity(UserActionTypes.UpdateSubCategory)]
        public async Task<IActionResult> UpdateSubCategory(SubCategoryVm subCategoryVm)
        {
            var categoryDdlList = await _commonddlService.GetCategoryDDL();
            ViewBag.categoryDdlList = new SelectList(categoryDdlList, "Value", "Text");
            if (!ModelState.IsValid)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView();
            }
            else
            {
                var responseMessage = await _subCategoryServices.SaveSubCategory(subCategoryVm);
                if (responseMessage.ReturnId > 0)
                {
                    _notyfService.Success(responseMessage.Msg);
                    return Ok();
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    var errors = new List<string> { responseMessage.Msg };
                    ViewBag.Error = errors;
                    return PartialView();
                }
            }

        }
        #endregion

        #region Delete SubCategory

        [HttpGet]
        public async Task<IActionResult> DeleteSubCategory(int Id)
        {
            var data = await _subCategoryServices.GetSubCategoryById(Id);
            return PartialView(data);
        }
        [HttpPost]
        [LogUserActivity(UserActionTypes.DeleteSubCategory)]
        public async Task<IActionResult> DeleteSubCategory(SubCategoryVm subCategoryVm)
        {
            var responseMessage = await _subCategoryServices.DeleteSubCategory(subCategoryVm.Id);
            if (responseMessage.ReturnId > 0)
            {
                _notyfService.Success(responseMessage.Msg);
                return Ok();
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            var errors = new List<string> { responseMessage.Msg };
            ViewBag.Error = errors;
            return PartialView();
        }
        #endregion

        #region Update Status
        [HttpPost]
        [LogUserActivity(UserActionTypes.UpdateSubCategoryStatus)]
        public async Task<IActionResult> UpdateStatus(int Id, bool IsActive)
        {
            var tableFlag = "tbl_SubCategory";
            var responseMessage = await _commonServices.UpdateStatus(Id, tableFlag, IsActive);
            if (responseMessage.ReturnId > 0)
            {
                _notyfService.Success(responseMessage.Msg);
                return Ok();
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            var errors = new List<string> { responseMessage.Msg };
            ViewBag.Error = errors;
            return PartialView();
        }
        #endregion
    }
}

FAMAndIMS/Views/SubCategory/DeleteSubCategory.cshtml
@using FAMAndIMS.Data.Model.GlobalSettingModel.SubCategoryModel
@model SubCategoryVm
<form id="formDeleteSubCategory" method="post" autocomplete="off" class="text-center">
    <input type="hidden" asp-for="Id" />
    <i class="fa fa-circle-xmark text-danger fa-5x mb-20 m-t-15 "></i>
    <h3 class="m-t-25">Are you sure?</h3>
    <p class="m-t-25 m-b-15">
        Do you really want to delete these records?<br>
        This process cannot be undone
    </p>

    <div class="modal-footer">
        <button type="button" class="btn btn-sm btn-light" data-bs-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-sm btn-primary">Delete</button>
    </div>
</form>

<script>

    FormHandler.init({
        method: 'POST',
        actionUrl: '@Url.Action("DeleteSubCategory", "SubCategory")',
        containerSelector: '#add-new .modal-body',
        selector: '#formDeleteSubCategory'
    }, function () {
        $("#add-new .modal-body").html("");
        $("#add-new .modal-title").html("");
        $("#add-new").modal('hide');
        Pagination.getData();
    });
</script>

FAMAndIMS/Views/SubCategory/Index.cshtml
@using FAMAndIMS.Data.Model.GlobalSettingModel.SubCategoryModel
@using FAMAndIMS.Data.Model.Paging
@model PagedResponse<SubCategoryListModel>

<div class="d-flex align-items-center justify-content-between mb-4">
    <div>
        <ol class="breadcrumb fs-sm mb-1">
            <li class="breadcrumb-item"><a href="#">SubCategory Setup</a></li>
            <li class="breadcrumb-item active" aria-current="page">SubCategory</li>
        </ol>
    </div>
</div>


<div class="card card-one mt-3">
    <div class="card-header">
        <h6 class="card-title">SubCategory</h6>
        <nav class="nav nav-icon nav-icon-sm ms-auto">
            @if (ViewBag.create)
            {
                <a style="cursor:pointer" onclick="ShowPopUp('@Url.Action("SaveSubCategory","SubCategory")','Add SubCategory')" class="btn btn-primary btn-icons"><i class="ri-add-fill"></i> Add SubCategory</a>
            }
        </nav>
    </div>
    <div class="card-body p-3">
        <partial name="_PaginationHeader" />
        <div class="table-responsive" id="SubCategoryTableWrapper">
            <partial name="_SubCategoryIndex" model="@Model" />
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            // Initialize pagination settings object
            Pagination.init({
                ajax: true,
                method: 'GET',
                browserPath: '@Context.Request.Path',
                fetchUrl: '@Url.Action("Index", "SubCategory")',
                selector: '#SubCategoryTableWrapper'
            });

            // attach 'before' event handler to 'Pagination' object to get all field parameters for pagination
            $(Pagination).on('before', function (e) {
                e.preventDefault();

                var usersFilterFormValues = $('#FormCashtypefilter').serializeArray();
                $.each(usersFilterFormValues, function (i, obj) {
                    e.payload.paramsBuilder.addParameter(obj['name'], obj['value']);
                });

                e.payload.paramsBuilder.addParameters(getPaginationFieldParams());
            });

            addUsersPageHandlers();
            addPaginationHandlers();
            function addUsersPageHandlers() {
            }
        });

    </script>
}

FAMAndIMS/Views/SubCategory/SaveSubCategory.cshtml
@using FAMAndIMS.Data.Model.GlobalSettingModel.SubCategoryModel
@model SubCategoryVm
<form id="saveSubCategory" enctype="multipart/form-data" class="form-horizontal auth-form" method="post" autocomplete="off">
    <div class="card card-one">
        <ul>
            @if (ViewBag.Error is not null)
            {
                @foreach (var error in ViewBag.Error)
                {
                    <li class="text-danger">@error</li>
                }
            }
        </ul>
        <div class="card-body p-3">
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        <label for="SubCategoryName" class="form-label">SubCategory Name<span style="color:firebrick">*</span></label>
                        <input asp-for="SubCategoryName" type="text" class="form-control" id="SubCategoryName" placeholder="">
                        <span class="text-danger" asp-validation-for="SubCategoryName"></span>
                    </div>
                    <div class="form-check form-switch">
                        <input asp-for="IsActive" class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                        <label class="form-check-label" for="flexSwitchCheckDefault">Is Active</label>
                        <span class="text-danger" asp-validation-for="IsActive"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label class="form-label" for="CategoryId">Category<span style="color:firebrick">*</span></label>
                        <select asp-for="CategoryId" id="CategoryId" class="form-select form-control" asp-items="ViewBag.categoryDdlList" aria-label="form-select-lg example">
                            <option value="0"> Select Category </option>
                        </select>
                        <span class="text-danger" asp-validation-for="CategoryId"></span>
                    </div>
                </div>

            </div>
        </div>
        <div class="modal-footer mt-3">
            <button type="button" class="btn btn-dark waves-effect" data-bs-dismiss="modal">Cancel</button>
            <button class="btn btn-primary" type="submit">Submit <i class="ri-send-plane-fill"></i></button>
        </div>
        <!-- card-body -->
    </div><!-- card -->
    </div>
</form>
<script>

    FormHandler.init({
        method: 'POST',
        actionUrl: '@Url.Action("SaveSubCategory", "SubCategory")',
        containerSelector: '#add-new .modal-body',
        selector: '#saveSubCategory'
    }, function () {
        $("#add-new .modal-body").html("");
        $("#add-new .modal-title").html("");
        $("#add-new").modal('hide');

        Pagination.getData();
    });
    $(document).ready(function () {
        document.getElementById("flexSwitchCheckDefault").checked = true;
    })
</script>

FAMAndIMS/Views/SubCategory/UpdateSubCategory.cshtml
@using FAMAndIMS.Data.Model.GlobalSettingModel.SubCategoryModel
@model SubCategoryVm
<form id="updateSubCategory" enctype="multipart/form-data" class="form-horizontal auth-form" method="post" autocomplete="off">
    <div class="card card-one">
        <ul>
            @if (ViewBag.Error is not null)
            {
                @foreach (var error in ViewBag.Error)
                {
                    <li class="text-danger">@error</li>
                }
            }
        </ul>
        <div class="card-body p-3">
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        <label for="SubCategoryName" class="form-label">SubCategory Name<span style="color:firebrick">*</span></label>
                        <input asp-for="SubCategoryName" type="text" class="form-control" id="SubCategoryName" placeholder="">
                        <span class="text-danger" asp-validation-for="SubCategoryName"></span>
                    </div>
                    <div class="form-check form-switch">
                        <input asp-for="IsActive" class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                        <label class="form-check-label" for="flexSwitchCheckDefault">Is Active</label>
                        <span class="text-danger" asp-validation-for="IsActive"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label class="form-label" for="CategoryId">Category<span style="color:firebrick">*</span></label>
                        <select asp-for="CategoryId" id="CategoryId" class="form-select form-control" asp-items="ViewBag.categoryDdlList" aria-label="form-select-lg example">
                            <option value="0"> Select Category </option>
                        </select>
                        <span class="text-danger" asp-validation-for="CategoryId"></span>
                    </div>
                </div>

            </div>
        </div>
        <div class="modal-footer mt-3">
            <button type="button" class="btn btn-dark waves-effect" data-bs-dismiss="modal">Cancel</button>
            <button class="btn btn-primary" type="submit">Submit <i class="ri-send-plane-fill"></i></button>
        </div>
        <!-- card-body -->
    </div><!-- card -->
    </div>
</form>
<script>

    FormHandler.init({
        method: 'POST',
        actionUrl: '@Url.Action("UpdateSubCategory", "SubCategory")',
        containerSelector: '#add-new .modal-body',
        selector: '#updateSubCategory'
    }, function () {
        $("#add-new .modal-body").html("");
        $("#add-new .modal-title").html("");
        $("#add-new").modal('hide');

        Pagination.getData();
    });
</script>

FAMAndIMS/Views/SubCategory/_SubCategoryIndex.cshtml
@using FAMAndIMS.Data.Model.GlobalSettingModel.SubCategoryModel
@using FAMAndIMS.Data.Model.Paging
@using FAMAndIMS.Models.Pagination
@model PagedResponse<SubCategoryListModel>
@{
    int Sn = 1;
}
<table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
    <thead>
        <tr>
            <th scope="col">SN</th>
            <th scope="col">SubCategory Name</th>
            <th scope="col">Category Name</th>
            <th scope="col">Is Active </th>
            <th scope="col">Action  </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <th scope="row">@Sn</th>
                <td>
                    @item.SubCategoryName
                </td>
                <td>
                    @item.CategoryName
                </td>
                @if (ViewBag.update)
                {
                    @if (item.IsActive)
                    {
                        <td>
                            <div class="form-check form-switch">
                                <input asp-for="@item.IsActive" class="form-check-input bg-success statusCheckBox" type="checkbox" id="" onchange="changeStatus(@item.Id, this.checked,'SubCategory','UpdateStatus')">
                            </div>
                        </td>
                    }
                    else
                    {
                        <td>
                            <div class="form-check form-switch ">
                                <input asp-for="@item.IsActive" class="form-check-input bg-danger statusCheckBox" type="checkbox" id="" onchange="changeStatus(@item.Id, this.checked,'SubCategory','UpdateStatus')">
                            </div>
                        </td>
                    }
                }
                else
                {
                    var colorClassName = item.IsActive == true ? "bg-success" : "bg-danger";
                    <td>
                        <div class="form-check form-switch ">
                            <input asp-for="@item.IsActive" class="form-check-input bg-danger statusCheckBox" type="checkbox" id="" readonly>
                        </div>
                    </td>
                }
                <td>
                    @if (ViewBag.update == true)
                    {
                        <button id="bEdit" style="cursor: pointer;" type="button" class="btn" data-toggle="tooltip" title="Edit SubCategory" onclick="ShowPopUp('@Url.Action("UpdateSubCategory", "SubCategory", new { Id = item.Id })', 'Edit SubCategory','modal-dialog modal-md')"><i class="ri-edit-2-line"></i></button>

                        @* <a style="cursor: pointer;" onclick="ShowPopUp('@Url.Action("UpdateSubCategory","SubCategory",new {id=item.Id })','Edit SubCategory')" class="dropdown-item rename"><i class="ri-edit-2-line"></i> </a> *@
                    }
                    @if (ViewBag.delete == true)
                    {
                        <button id="bEdit" style="cursor: pointer;" type="button" class="btn" data-toggle="tooltip" title="Delete SubCategory" onclick="ShowPopUp('@Url.Action("DeleteSubCategory", "SubCategory", new { Id = item.Id })', 'Delete SubCategory','modal-dialog modal-md')"><i class="ri-delete-bin-line"></i></button>

                        @* <a style="cursor: pointer;" onclick="ShowPopUp('@Url.Action("DeleteSubCategory","SubCategory",new {id=item.Id })','Delete SubCategory', 'modal-dialog modal-md')" class="dropdown-item delete"><i class="ri-delete-bin-line"></i> </a> *@
                    }
                </td>
            </tr>
            Sn = Sn + 1;
        }


    </tbody>
</table>
<partial name="_PaginationFooter"
         model="new PaginationFooter(Model.PageNumber, Model.PageSize, Model.Items.Count(), Model.FilteredCount, Model.TotalCount, Model.TotalPages)" />