FAMAndIMS/Controllers/AssetManagementController/AssetsController/AssetsController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using FAMAndIMS.Common;
using FAMAndIMS.Data.Model.AssetManagementModel.AssetsModel;
using FAMAndIMS.Data.Model.AssetManagementModel.AssetsModel.GeneratedDepreciationModel;
using FAMAndIMS.Data.Model.CommonModel;
using FAMAndIMS.Data.Services.AssetManagementServices.AssetsServices;
using FAMAndIMS.Data.Services.CommonddlServices;
using FAMAndIMS.Data.Services.CommonServices;
using FAMAndIMS.Extension;
using FAMAndIMS.Filter;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using System.Net;

namespace FAMAndIMS.Controllers.AssetManagementController.AssetsController
{
    [Authorize]
    public class AssetsController : Controller
    {
        private readonly INotyfService _notyfService;
        private readonly IAssetsServices _assetsServices;
        private readonly ICommonddlService _commonddlService;
        private readonly ICommonServices _commonServices;

        public AssetsController(INotyfService notyfService, IAssetsServices assetsServices, ICommonddlService commonddlService, ICommonServices commonServices)
        {
            _notyfService = notyfService;
            _assetsServices = assetsServices;
            _commonddlService = commonddlService;
            _commonServices = commonServices;
        }
        #region Index
        [MenuAccess]
        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] AssetsDto assetsDto)
        {
            Response.Headers["Cache-Control"] = "no-store, no-cache, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "0";
            ViewBag.view = HttpContext.Items["view"];
            ViewBag.create = HttpContext.Items["create"];
            ViewBag.delete = HttpContext.Items["delete"];
            ViewBag.update = HttpContext.Items["update"];
            var assetsList = await _assetsServices.GetAssetsList(assetsDto);
            if (WebHelper.IsAjaxRequest(Request))
            {
                return PartialView("_AssetsIndex", assetsList);
            }
            return View(assetsList);

        }
        #endregion

        #region Save Asset 
        [HttpGet]
        public async Task<IActionResult> SaveAssets()
        {
            var unitDdlList = await _commonddlService.GetUnitDDL();
            ViewBag.unitDdlList = new SelectList(unitDdlList, "Value", "Text");
            var categoryDdlList = await _commonddlService.GetCategoryDDL();
            ViewBag.categoryDdlList = new SelectList(categoryDdlList, "Value", "Text");
            var subCategoryDdlList = await _commonddlService.GetSubCategoryDDL();
            ViewBag.subCategoryDdlList = new SelectList(subCategoryDdlList, "Value", "Text");
            var vendorDdlList = await _commonddlService.GetVendorDDL();
            ViewBag.vendorDdlList = new SelectList(vendorDdlList, "Value", "Text");
            var employeeDdlList = await _commonddlService.GetEmployeeDDL();
            ViewBag.employeeDdlList = new SelectList(employeeDdlList, "Value", "Text");
            var depreciationTypeDdlList = await _commonddlService.GetDepreciationDDL();
            ViewBag.depreciationTypeDdlList = new SelectList(depreciationTypeDdlList, "Value", "Text");
            var conditionDdlList = await _commonddlService.GetConditionDDL();
            ViewBag.conditionDdlList = new SelectList(conditionDdlList, "Value", "Text");
            var branchDdlList = await _commonddlService.GetBranchDDL();
            ViewBag.branchDdlList = new SelectList(branchDdlList, "Value", "Text");
            var departmentDdlList = await _commonddlService.GetDepartmentDDL();
            ViewBag.departmentDdlList = new SelectList(departmentDdlList, "Value", "Text");
            return View();
        }
        [HttpPost]
        [LogUserActivity(UserActionTypes.SaveAssets)]
        public async Task<IActionResult> SaveAssets(AssetsVM assetsVM)
        {
            var unitDdlList = await _commonddlService.GetUnitDDL();
            ViewBag.unitDdlList = new SelectList(unitDdlList, "Value", "Text");
            var categoryDdlList = await _commonddlService.GetCategoryDDL();
            ViewBag.categoryDdlList = new SelectList(categoryDdlList, "Value", "Text");
            var subCategoryDdlList = await _commonddlService.GetSubCategoryDDL();
            ViewBag.subCategoryDdlList = new SelectList(subCategoryDdlList, "Value", "Text");
            var vendorDdlList = await _commonddlService.GetVendorDDL();
            ViewBag.vendorDdlList = new SelectList(vendorDdlList, "Value", "Text");
            var employeeDdlList = await _commonddlService.GetEmployeeDDL();
            ViewBag.employeeDdlList = new SelectList(employeeDdlList, "Value", "Text");
            var depreciationTypeDdlList = await _commonddlService.GetDepreciationDDL();
            ViewBag.depreciationTypeDdlList = new SelectList(depreciationTypeDdlList, "Value", "Text");
            var conditionDdlList = await _commonddlService.GetConditionDDL();
            ViewBag.conditionDdlList = new SelectList(conditionDdlList, "Value", "Text");
            var branchDdlList = await _commonddlService.GetBranchDDL();
            ViewBag.branchDdlList = new SelectList(branchDdlList, "Value", "Text");
            var departmentDdlList = await _commonddlService.GetDepartmentDDL();
            ViewBag.departmentDdlList = new SelectList(departmentDdlList, "Value", "Text");
            if (!ModelState.IsValid)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return View();
            }
            else
            {
                var responseMessage = await _assetsServices.SaveAssets(assetsVM);
                if (responseMessage.ReturnId > 0)
                {
                    _notyfService.Success(responseMessage.Msg);
                    return RedirectToAction("Index");
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    var errors = new List<string> { responseMessage.Msg };
                    ViewBag.Error = errors;
                    return View();
                }
            }
        }
        #endregion

        #region Update Assets

        [HttpGet]
        public async Task<IActionResult> UpdateAssets(int id)
        {
            var unitDdlList = await _commonddlService.GetUnitDDL();
            ViewBag.unitDdlList = new SelectList(unitDdlList, "Value", "Text");
            var categoryDdlList = await _commonddlService.GetCategoryDDL();
            ViewBag.categoryDdlList = new SelectList(categoryDdlList, "Value", "Text");
            var subCategoryDdlList = await _commonddlService.GetSubCategoryDDL();
            ViewBag.subCategoryDdlList = new SelectList(subCategoryDdlList, "Value", "Text");
            var vendorDdlList = await _commonddlService.GetVendorDDL();
            ViewBag.vendorDdlList = new SelectList(vendorDdlList, "Value", "Text");
            var employeeDdlList = await _commonddlService.GetEmployeeDDL();
            ViewBag.employeeDdlList = new SelectList(employeeDdlList, "Value", "Text");
            var depreciationTypeDdlList = await _commonddlService.GetDepreciationDDL();
            ViewBag.depreciationTypeDdlList = new SelectList(depreciationTypeDdlList, "Value", "Text");
            var conditionDdlList = await _commonddlService.GetConditionDDL();
            ViewBag.conditionDdlList = new SelectList(conditionDdlList, "Value", "Text");
            var branchDdlList = await _commonddlService.GetBranchDDL();
            ViewBag.branchDdlList = new SelectList(branchDdlList, "Value", "Text");
            var departmentDdlList = await _commonddlService.GetDepartmentDDL();
            ViewBag.departmentDdlList = new SelectList(departmentDdlList, "Value", "Text");
            var data = await _assetsServices.GetAssetsById(id);
            return View(data);
        }

        [HttpPost]
        [LogUserActivity(UserActionTypes.UpdateAssets)]
        public async Task<IActionResult> UpdateAssets(AssetsVM assetsVM)
        {
            var unitDdlList = await _commonddlService.GetUnitDDL();
            ViewBag.unitDdlList = new SelectList(unitDdlList, "Value", "Text");
            var categoryDdlList = await _commonddlService.GetCategoryDDL();
            ViewBag.categoryDdlList = new SelectList(categoryDdlList, "Value", "Text");
            var subCategoryDdlList = await _commonddlService.GetSubCategoryDDL();
            ViewBag.subCategoryDdlList = new SelectList(subCategoryDdlList, "Value", "Text");
            var vendorDdlList = await _commonddlService.GetVendorDDL();
            ViewBag.vendorDdlList = new SelectList(vendorDdlList, "Value", "Text");
            var employeeDdlList = await _commonddlService.GetEmployeeDDL();
            ViewBag.employeeDdlList = new SelectList(employeeDdlList, "Value", "Text");
            var depreciationTypeDdlList = await _commonddlService.GetDepreciationDDL();
            ViewBag.depreciationTypeDdlList = new SelectList(depreciationTypeDdlList, "Value", "Text");
            var conditionDdlList = await _commonddlService.GetConditionDDL();
            ViewBag.conditionDdlList = new SelectList(conditionDdlList, "Value", "Text");
            var branchDdlList = await _commonddlService.GetBranchDDL();
            ViewBag.branchDdlList = new SelectList(branchDdlList, "Value", "Text");
            var departmentDdlList = await _commonddlService.GetDepartmentDDL();
            ViewBag.departmentDdlList = new SelectList(departmentDdlList, "Value", "Text");
            if (!ModelState.IsValid)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return View();
            }
            else
            {
                var responseMessage = await _assetsServices.SaveAssets(assetsVM);

FAMAndIMS/Views/Assets/DeleteAssets.cshtml
@using FAMAndIMS.Data.Model.AssetManagementModel.AssetsModel
@model AssetsVM
<form id="formDeleteAssets" method="post" autocomplete="off" class="text-center">
    <input type="hidden" asp-for="Id" />
    <i class="fa fa-circle-xmark text-danger fa-5x mb-20 m-t-15 "></i>
    <h3 class="m-t-25">Are you sure?</h3>
    <p class="m-t-25 m-b-15">
        Do you really want to delete these records?<br>
        This process cannot be undone
    </p>

    <div class="modal-footer">
        <button type="button" class="btn btn-sm btn-light" data-bs-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-sm btn-primary">Delete</button>
    </div>
</form>

<script>

    FormHandler.init({
        method: 'POST',
        actionUrl: '@Url.Action("DeleteAssets", "Assets")',
        containerSelector: '#add-new .modal-body',
        selector: '#formDeleteAssets'
    }, function () {
        $("#add-new .modal-body").html("");
        $("#add-new .modal-title").html("");
        $("#add-new").modal('hide');
        Pagination.getData();
    });
</script>

FAMAndIMS/Views/Assets/GenerateDepreciation.cshtml
@using FAMAndIMS.Data.Model.AssetManagementModel.AssetsModel.GeneratedDepreciationModel
@using FAMAndIMS.Data.Model.Paging
@model PagedResponse<GeneratedDepreciationList>

<div class="d-flex align-items-center justify-content-between mb-4">
    <div>
        <ol class="breadcrumb fs-sm mb-1">
            <li class="breadcrumb-item"><a href="#">Assets Setup</a></li>
            <li class="breadcrumb-item active" aria-current="page">Assets</li>
        </ol>
    </div>
</div>


<div class="card card-one mt-3">
    <div class="card-header">
        <h6 class="card-title">Assets</h6>
        <nav class="nav nav-icon nav-icon-sm ms-auto">
      @*       <form id="formGeneratedDepreciationListFilter" class="row row-cols-lg-auto align-items-center">
                <div>
                    <div class="input-group">

                        <select name="Event" id="Event" class="form-select">
                            <option value="All">All</option>
                            <option value="CategoryWise">Category Wise</option>
                        </select>
                    </div>
                </div>
                <div>
                    <div class="input-group">
                        <select name="CategoryId" id="CategoryId" asp-items="ViewBag.CategoryDDLList" class="form-select">
                            <option value="All">Select Category</option>
                        </select>
                    </div>
                </div>
                <div>
                    <div class="input-group">
                        <input name="AssetCode" type="text" class="form-control" id="AssetCode" placeholder="Asset Code" />
                    </div>
                </div>
                <div>
                    <div class="input-group">
                        <input name="FromDate" type="datetime-local" id="FromDate" onkeydown="return false" class="form-control" data-single-mode="true">
                    </div>
                </div>
                <div>
                    <div class="input-group">
                        <input name="ToDate" type="datetime-local" id="StToDateartDate" onkeydown="return false" class="form-control" data-single-mode="true">
                    </div>
                </div>
                <div class="m-2">
                    <button id="btnGeneratedDepreciation" type="button" class="btn btn-primary"><i class="las la-filter ms-1"></i> Filter</button>
                </div>
            </form> *@
            <div class="m-2">
                <a id="btnexportexcelDepreciationList" class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Export To Excel"><i data-placement="top" data-original-title="Export To Excell" data-feather="file-text"></i>Excel</a>
            </div>
            <div class="m-2">
                <a id="btnexportPdfDepreciationList" class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Export To Pdf"><i data-feather="file-text"></i>PDF</a>
            </div>
            <div class="m-2">
                <a id="btnexportcsvDepreciationList" class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Export To Csv" data-placement="top"><i data-feather="file-text"></i>CSV</a>
            </div>
        </nav>
    </div>
    <div class="card-body p-3">
        <partial name="_PaginationHeader" />
        <div class="table-responsive" id="GeneratedDepreciationTableWrapper">
            <partial name="_GenerateDepreciation" model="@Model" />
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            //hiding the category dropdown
            var categoryDropdown = document.getElementById("CategoryId").parentElement;
            categoryDropdown.style.display = "none";
            // Initialize pagination settings object
            Pagination.init({
                ajax: true,
                method: 'GET',
                browserPath: '@Context.Request.Path',
                fetchUrl: '@Url.Action("GenerateDepreciation", "Assets")',
                selector: '#GeneratedDepreciationTableWrapper'
            });

            // attach 'before' event handler to 'Pagination' object to get all field parameters for pagination
            $(Pagination).on('before', function (e) {
                e.preventDefault();

                var usersFilterFormValues = $('#formGeneratedDepreciationListFilter').serializeArray();
                $.each(usersFilterFormValues, function (i, obj) {
                    e.payload.paramsBuilder.addParameter(obj['name'], obj['value']);
                });

                e.payload.paramsBuilder.addParameters(getPaginationFieldParams());
            });

            addUsersPageHandlers();
            addPaginationHandlers();
            function addUsersPageHandlers() {

                /* Custom Handlers */
                $('#formGeneratedDepreciationListFilter').on('submit', function (e) {
                    e.preventDefault();
                    e.stopPropagation();
                })

                $('#btnGeneratedDepreciation').on('click', function (e) {
                    e.preventDefault();
                    Pagination.getData();
                    return false;
                });

                $('#btnexportexcelDepreciationList').on('click', function (e) {
                    e.preventDefault();
                    var paramsA = {
                        IsExport: 1
                    };
                    Pagination.ExportDataWithPagination('GET', paramsA, '@Url.Action("GenerateDepreciationListExportExcel", "Assets")');
                    return false;
                });
                $('#btnexportPdfDepreciationList').on('click', function (e) {
                    e.preventDefault();
                    var paramsA = {
                        IsExport: 1
                    };
                    Pagination.ExportDataWithPagination('GET', paramsA, '@Url.Action("GenerateDepreciationListsExportPdf", "Assets")');
                    return false;
                });
                $('#btnexportcsvDepreciationList').on('click', function (e) {
                    e.preventDefault();
                    var paramsA = {
                        IsExport: 1
                    };
                    Pagination.ExportDataWithPagination('GET', paramsA, '@Url.Action("GenerateDepreciationListExportCsv", "Assets")');
                    return false;
                });
            }
        });

        document.addEventListener("DOMContentLoaded", function () {
            var eventDropdown = document.getElementById("Event");
            var categoryDropdown = document.getElementById("CategoryId").parentElement; // Getting the parent div

            function toggleCategoryDropdown() {
                if (eventDropdown.value === "CategoryWise") {
                    categoryDropdown.style.display = "flex";
                } else {
                    categoryDropdown.style.display = "none";
                }
            }

            eventDropdown.addEventListener("change", toggleCategoryDropdown);
            toggleCategoryDropdown(); // Call once on page load
        });
    </script>
}

FAMAndIMS/Views/Assets/Index.cshtml
@using FAMAndIMS.Data.Model.AssetManagementModel.AssetsModel
@using FAMAndIMS.Data.Model.Paging
@model PagedResponse<AssetsListModel>

<div class="d-flex align-items-center justify-content-between mb-4">
    <div>
        <ol class="breadcrumb fs-sm mb-1">
            <li class="breadcrumb-item"><a href="#">Assets Setup</a></li>
            <li class="breadcrumb-item active" aria-current="page">Assets</li>
        </ol>
    </div>
</div>


<div class="card card-one mt-3">
    <div class="card-header">
        <h6 class="card-title">Assets</h6>
        <nav class="nav nav-icon nav-icon-sm ms-auto">
            <div class="m-2">
                <a id="btnexportexcelAssetsList" asp-controller="Assets" asp-action="" value="@ViewBag.IsExportExcel" class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Export To Excell"><i data-placement="top" data-original-title="Export To Excell" data-feather="file-text"></i>Excel</a>
            </div>
            <div class="m-2">
                <a id="btnexportPdfAssetsList" value="@ViewBag.IsExportPdf" class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Export To Pdf"><i data-feather="file-text"></i>PDF</a>
            </div>
            <div class="m-2">
                <a id="btnexportcsvAssetsList" value="@ViewBag.IsExportCSV" class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Export To Csv" data-placement="top"><i data-feather="file-text"></i>CSV</a>
            </div>
            <div class="m-2">
                @if (ViewBag.create)
                {
                    <a style="cursor:pointer" asp-controller="Assets" asp-action="GenerateDepreciation" class="btn btn-warning btn-icons me-3"><i class="ri-ticket-2-line"></i> Generate Depreciation</a>
                }
                @if (ViewBag.create)
                {
                    <a style="cursor:pointer" asp-controller="Assets" asp-action="SaveAssets" class="btn btn-primary btn-icons"><i class="ri-add-fill"></i> Add Assets</a>
                }
            </div>
            @* <div class="m-2">
            @if (ViewBag.create)
            {
            <a style="cursor:pointer" onclick="ShowPopUp('@Url.Action("UploadBulkExcel","AssetInsurance")','Bulk Upload Excel','modal-dialog modal-md')" class="btn btn-primary btn-icons"><i class="ri-add-fill"></i> Bulk Upload Excel</a>
            }
            </div> *@
        </nav>
    </div>
    <div class="card-body p-3">
        <partial name="_PaginationHeader" />
        <div class="table-responsive" id="AssetsTableWrapper">
            <partial name="_AssetsIndex" model="@Model" />
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            // Initialize pagination settings object
            Pagination.init({
                ajax: true,
                method: 'GET',
                browserPath: '@Context.Request.Path',
                fetchUrl: '@Url.Action("Index", "Assets")',
                selector: '#AssetsTableWrapper'
            });

            // attach 'before' event handler to 'Pagination' object to get all field parameters for pagination
            $(Pagination).on('before', function (e) {
                e.preventDefault();

                var usersFilterFormValues = $('#FormCashtypefilter').serializeArray();
                $.each(usersFilterFormValues, function (i, obj) {
                    e.payload.paramsBuilder.addParameter(obj['name'], obj['value']);
                });

                e.payload.paramsBuilder.addParameters(getPaginationFieldParams());
            });

            addUsersPageHandlers();
            addPaginationHandlers();
            function addUsersPageHandlers() {
                $('#btnexportexcelAssetsList').on('click', function (e) {
                    e.preventDefault();
                    var paramsA = {
                        IsExport: 1
                    };
                    Pagination.ExportDataWithPagination('GET', paramsA, '@Url.Action("AssetsListExportExcell", "Assets")');
                    return false;
                });
                $('#btnexportPdfAssetsList').on('click', function (e) {
                    e.preventDefault();
                    var paramsA = {
                        IsExport: 1
                    };
                    Pagination.ExportDataWithPagination('GET', paramsA, '@Url.Action("AssetsListsExportPdf", "Assets")');
                    return false;
                });
                $('#btnexportcsvAssetsList').on('click', function (e) {
                    e.preventDefault();
                    var paramsA = {
                        IsExport: 1
                    };
                    Pagination.ExportDataWithPagination('GET', paramsA, '@Url.Action("AssetsListExportCsv", "Assets")');
                    return false;
                });
            }
        });

    </script>
}

FAMAndIMS/Views/Assets/_AssetsIndex.cshtml
@using FAMAndIMS.Data.Model.AssetManagementModel.AssetsModel
@using FAMAndIMS.Data.Model.Paging
@using FAMAndIMS.Models.Pagination
@model PagedResponse<AssetsListModel>
@{
    int Sn = 1;
}
<table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
    <thead>
        <tr>
            <th scope="col">SN</th>
            <th scope="col">Asset Name</th>
            <th scope="col">Asset Code</th>
            <th scope="col">Bar Code</th>
            <th scope="col">Purchase Date</th>
            <th scope="col">Purchase Date BS</th>
            <th scope="col">Allocate Date</th>
            <th scope="col">Allocate Date BS</th>
            <th scope="col">Unit</th>
            <th scope="col">Category</th>
            <th scope="col">SubCategory</th>
            <th scope="col">SerialNo</th>
            <th scope="col">Vendor</th>
            <th scope="col">Employee</th>
            <th scope="col">Depreciation Type</th>
            <th scope="col">Condition</th>
            <th scope="col">Branch</th>
            <th scope="col">Department</th>
            <th scope="col">Opening Amount</th>
            <th scope="col">Accumulated Depreciation Amount</th>
            <th scope="col">Salvage Amount</th>
            <th scope="col">Depreciation Rate(in %)</th>
            <th scope="col">Adjustment Amount</th>
            <th scope="col">Additional Cost Amount</th>
            <th scope="col">Additional Cost Date</th>
            <th scope="col">Deletion Amount</th>
            <th scope="col">Deletion Date</th>
            <th scope="col">Depreciation Charge Till LastMonth</th>
            <th scope="col">Depreciation Charge Till Today</th>
            <th scope="col">Depreciation Run Date</th>
            <th scope="col">Current Month Charge Amount</th>
            <th scope="col">ProfitLoss Amount</th>
            <th scope="col">Maintenance Cost Amount</th>
            <th scope="col">Useful Life</th>
            <th scope="col">Last Maintenance Date</th>
            <th scope="col">Next Maintenance Date</th>
            <th scope="col">Image</th>
            <th scope="col">Remarks</th>
            <th scope="col">Is Active </th>
            <th scope="col">Action  </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <th scope="row">@Sn</th>
                <td>
                    @item.AssetsName
                </td>
                <td>@item.AssetCode</td>
                <td>
                    @if (!string.IsNullOrEmpty(item.BarCode))
                    {
                        <img src="@item.BarCode" alt="BarCode" class="rounded thumb-lg me-1" />
                    }

                </td>
                <td>@item.PurchaseDate.ToString("yyyy-MM-dd")</td>
                <td>@item.PurchaseDateBS</td>
                <td>@item.AllocateDate.ToString("yyyy-MM-dd")</td>
                <td>@item.AllocateDateBS</td>
                <td>@item.UnitType</td>
                <td>@item.Category</td>
                <td>@item.SubCategory</td>
                <td>@item.SerialNumber</td>
                <td>@item.Vendor</td>
                <td>@item.Employee</td>
                <td>@item.DepreciationType</td>
                <td>@item.ConditionStatus</td>
                <td>@item.Branch</td>
                <td>@item.Department</td>
                <td>@item.OpeningAmount</td>
                <td>@item.AccumulatedDepreciationAmount</td>
                <td>@item.SalvageAmount</td>
                <td>@item.DepreciationRate%</td>
                <td>@item.AdjustmentAmount</td>
                <td>@item.AdditionalCostAmount</td>
                <td>@item.AdditionalCostDate.ToString("yyyy-MM-dd")</td>
                <td>@item.DeletionAmount</td>
                <td>@item.DeletionDate.ToString("yyyy-MM-dd")</td>
                <td>@item.DepreciationChargeTillLastMonth</td>
                <td>@item.DepreciationChargeTillToday</td>
                <td>@item.DepreciationRunDate.ToString("yyyy-MM-dd")</td>
                <td>@item.CurrentMonthChargeAmount</td>
                <td>@item.ProfitLossAmount</td>
                <td>@item.MaintenanceCostAmount</td>
                <td>@item.UsefulLife</td>
                <td>@item.LastMaintenanceDate.ToString("yyyy-MM-dd")</td>
                <td>@item.NextMaintenanceDate.ToString("yyyy-MM-dd")</td>

                <td>
                    @if (!string.IsNullOrEmpty(item.ImageOfAsset))
                    {
                        <img src="@item.ImageOfAsset" alt="Image Of Asset" class="rounded thumb-lg me-1"  height="200" width="200"/>
                    }
                    
                </td>
                <td>@item.Remarks</td>

                @if (ViewBag.update)
                {
                    @if (item.IsActive)
                    {
                        <td>
                            <div class="form-check form-switch">
                                <input asp-for="@item.IsActive" class="form-check-input bg-success statusCheckBox" type="checkbox" id="" onchange="changeStatus(@item.Id, this.checked,'Assets','UpdateStatus')">
                            </div>
                        </td>
                    }
                    else
                    {
                        <td>
                            <div class="form-check form-switch ">
                                <input asp-for="@item.IsActive" class="form-check-input bg-danger statusCheckBox" type="checkbox" id="" onchange="changeStatus(@item.Id, this.checked,'Assets','UpdateStatus')">
                            </div>
                        </td>
                    }
                }
                else
                {
                    var colorClassName = item.IsActive == true ? "bg-success" : "bg-danger";
                    <td>
                        <div class="form-check form-switch ">
                            <input asp-for="@item.IsActive" class="form-check-input bg-danger statusCheckBox" type="checkbox" id="" readonly>
                        </div>
                    </td>
                }
                <td>
                    @if (ViewBag.update == true)
                    {
                        <a style="cursor: pointer;" asp-controller="Assets" asp-action="UpdateAssets" asp-route-Id="@item.Id" class="btn" data-toggle="tooltip" title="Edit Assets">
                            <i class="ri-edit-2-line"></i> 
                        </a>
                    }
                    @if (ViewBag.delete == true)
                    {
                        <button id="bEdit" style="cursor: pointer;" type="button" class="btn" data-toggle="tooltip" title="Delete Assets" onclick="ShowPopUp('@Url.Action("DeleteAssets", "Assets", new { Id = item.Id })', 'Delete Assets','modal-dialog modal-md')"><i class="ri-delete-bin-line"></i></button>
                    }
                </td>
            </tr>
            Sn = Sn + 1;
        }


    </tbody>
</table>
<partial name="_PaginationFooter"
         model="new PaginationFooter(Model.PageNumber, Model.PageSize, Model.Items.Count(), Model.FilteredCount, Model.TotalCount, Model.TotalPages)" />